name: rdesktop

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-18.04
          - ubuntu-20.04
          - windows-2016
          - windows-2019
          - windows-2022
          # - macos-10.15
          # - macos-11
        go:
          - '1.16'
          - '1.17'
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Lint
        run: |
          go install golang.org/x/lint/golint@latest
          golint -set_exit_status ./...
          go install github.com/gordonklaus/ineffassign@latest
          ineffassign ./...

      - name: Test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: go test -v ./...
